import { existsSync } from "node:fs";

if (existsSync(".env")) {
  process.loadEnvFile();
}

type BlockDef =
  | { type: "divider" }
  | { type: "callout"; text: string; icon?: string }
  | { type: string; text: string };

function snap(title: string, icon: string, blockDefs: BlockDef[]) {
  return {
    title,
    icon,
    cover_url: null,
    is_full_width: false,
    font_family: "default",
    blocks: blockDefs.map((b, i) => {
      let content: Record<string, unknown> | null = null;
      if (b.type === "divider") {
        content = {};
      } else if (b.type === "callout") {
        const calloutB = b as { type: "callout"; text: string; icon?: string };
        content = calloutB.text
          ? { icon: calloutB.icon ?? "💡", color: "", text: [{ text: calloutB.text, marks: [] }] }
          : null;
      } else {
        const textB = b as { type: string; text: string };
        content = textB.text ? { text: [{ text: textB.text, marks: [] }] } : null;
      }
      return {
        id: crypto.randomUUID(),
        type: b.type,
        content,
        schema_version: 1,
        order_index: i,
        parent_block_id: null,
        children: [],
      };
    }),
    subpages: [],
    database_schema: null,
  };
}

// ── NOTE: No h1 block in any template — the page title IS the h1 ──────────────

const TEMPLATES: {
  name: string;
  description: string;
  category: "productivity" | "project_mgmt" | "sales" | "marketing" | "engineering";
  icon: string;
  blocks: BlockDef[];
}[] = [
  // ── Onboarding ────────────────────────────────────────────────────────────────
  {
    name: "Getting Started", description: "A quick tour of the basics — the default page for new workspaces.", category: "productivity", icon: "👋",
    blocks: [
      { type: "callout",   text: "This page is yours to edit, move, or delete — nothing here is permanent.", icon: "👋" },
      { type: "divider" },
      { type: "h2",        text: "✏️ Write anything" },
      { type: "todo",      text: "Type \"/\" anywhere to insert a heading, image, table, and more" },
      { type: "todo",      text: "Highlight text to add bold, italics, or a comment" },
      { type: "todo",      text: "Drag a block by its handle to reorder it" },
      { type: "h2",        text: "📄 Organize your work" },
      { type: "todo",      text: "Click \"+\" in the sidebar to create a new page" },
      { type: "todo",      text: "Nest pages inside each other to build a hierarchy" },
      { type: "todo",      text: "Use a database for tasks, projects, or anything you track in rows" },
      { type: "h2",        text: "👥 Bring your team in" },
      { type: "todo",      text: "Invite teammates from workspace settings" },
      { type: "todo",      text: "@mention someone to notify them" },
      { type: "todo",      text: "Leave a comment on any block to start a discussion" },
      { type: "h2",        text: "🚀 Move faster" },
      { type: "todo",      text: "Browse the template gallery for ready-made pages" },
      { type: "todo",      text: "Star pages you visit often for quick access" },
      { type: "divider" },
      { type: "paragraph", text: "Ready? Delete this page or keep it around as a reference." },
    ],
  },

  // ── Personal ─────────────────────────────────────────────────────────────────
  {
    name: "Daily Journal", description: "Date-stamped entries with mood, highlights, and reflection prompts.", category: "productivity", icon: "📔",
    blocks: [
      { type: "callout",   text: "📅 Date: _____________   ·   Mood: 😊 Happy  😐 Okay  😔 Tough   ·   Energy: ⚡ High  🔋 Medium  💤 Low", icon: "📔" },
      { type: "divider" },
      { type: "h2",        text: "🌅 Morning Intentions" },
      { type: "paragraph", text: "What do I want to accomplish today?" },
      { type: "bullet",    text: "Priority 1: " },
      { type: "bullet",    text: "Priority 2: " },
      { type: "bullet",    text: "Priority 3: " },
      { type: "h2",        text: "✨ Today's Highlights" },
      { type: "bullet",    text: "Something that went well: " },
      { type: "bullet",    text: "A challenging moment and what I learned: " },
      { type: "bullet",    text: "Something unexpected: " },
      { type: "h2",        text: "🙏 What I'm Grateful For" },
      { type: "bullet",    text: "1. " },
      { type: "bullet",    text: "2. " },
      { type: "bullet",    text: "3. " },
      { type: "h2",        text: "🌙 Evening Reflection" },
      { type: "paragraph", text: "How did today go overall?" },
      { type: "paragraph", text: "" },
      { type: "h3",        text: "What would I do differently?" },
      { type: "paragraph", text: "" },
      { type: "h3",        text: "Intentions for tomorrow" },
      { type: "bullet",    text: "" },
    ],
  },
  {
    name: "Weekly Planner", description: "Goals, schedule, and review sections for the week.", category: "productivity", icon: "📅",
    blocks: [
      { type: "callout",   text: "📅 Week of: _____________   ·   🎯 Theme / Focus: _____________", icon: "📅" },
      { type: "divider" },
      { type: "h2",        text: "🎯 Goals This Week" },
      { type: "todo",      text: "Goal 1: " },
      { type: "todo",      text: "Goal 2: " },
      { type: "todo",      text: "Goal 3: " },
      { type: "h2",        text: "📅 Daily Schedule" },
      { type: "h3",        text: "Monday" },
      { type: "bullet",    text: "Morning: " },
      { type: "bullet",    text: "Afternoon: " },
      { type: "h3",        text: "Tuesday" },
      { type: "bullet",    text: "Morning: " },
      { type: "bullet",    text: "Afternoon: " },
      { type: "h3",        text: "Wednesday" },
      { type: "bullet",    text: "Morning: " },
      { type: "bullet",    text: "Afternoon: " },
      { type: "h3",        text: "Thursday" },
      { type: "bullet",    text: "Morning: " },
      { type: "bullet",    text: "Afternoon: " },
      { type: "h3",        text: "Friday" },
      { type: "bullet",    text: "Morning: " },
      { type: "bullet",    text: "Afternoon: " },
      { type: "divider" },
      { type: "h2",        text: "📝 Week Review" },
      { type: "h3",        text: "What went well?" },
      { type: "bullet",    text: "" },
      { type: "h3",        text: "What could be improved?" },
      { type: "bullet",    text: "" },
      { type: "h3",        text: "Carry over to next week" },
      { type: "todo",      text: "" },
    ],
  },
  {
    name: "Reading List", description: "Track books with status, rating, and notes.", category: "productivity", icon: "📚",
    blocks: [
      { type: "paragraph", text: "Track every book — fiction, non-fiction, articles, and more." },
      { type: "divider" },
      { type: "h2",        text: "📖 Currently Reading" },
      { type: "callout",   text: "Book title — Author   |   Started: ______   |   Target finish: ______", icon: "📖" },
      { type: "paragraph", text: "Notes so far: " },
      { type: "h2",        text: "📚 Want to Read" },
      { type: "bullet",    text: "Book title — Author   |   Why: " },
      { type: "bullet",    text: "Book title — Author   |   Why: " },
      { type: "bullet",    text: "Book title — Author   |   Why: " },
      { type: "h2",        text: "✅ Finished" },
      { type: "bullet",    text: "Book title — Author   |   Rating: ⭐⭐⭐⭐⭐   |   Finished: ______" },
      { type: "bullet",    text: "Book title — Author   |   Rating: ⭐⭐⭐⭐☆   |   Finished: ______" },
      { type: "h2",        text: "💡 Notes & Highlights" },
      { type: "h3",        text: "Key quotes" },
      { type: "quote",     text: "Quote from the book..." },
      { type: "h3",        text: "Big ideas I'll remember" },
      { type: "bullet",    text: "" },
      { type: "h3",        text: "How I'll apply this" },
      { type: "paragraph", text: "" },
    ],
  },
  {
    name: "Habit Tracker", description: "Checkbox-based daily habit tracking.", category: "productivity", icon: "✅",
    blocks: [
      { type: "callout",   text: "📅 Month: _____________   ·   Goal: Build consistent routines that compound over time.", icon: "🎯" },
      { type: "divider" },
      { type: "h2",        text: "🌟 My Habits" },
      { type: "h3",        text: "Health & Body" },
      { type: "todo",      text: "Morning exercise (30 min)" },
      { type: "todo",      text: "Drink 8 glasses of water" },
      { type: "todo",      text: "Sleep 7–8 hours" },
      { type: "todo",      text: "No screens 1 hour before bed" },
      { type: "h3",        text: "Mind & Learning" },
      { type: "todo",      text: "Read for 30 minutes" },
      { type: "todo",      text: "Meditate (10 min)" },
      { type: "todo",      text: "Write in journal" },
      { type: "todo",      text: "Learn something new" },
      { type: "h3",        text: "Work & Productivity" },
      { type: "todo",      text: "Deep work block (2 hrs, no distractions)" },
      { type: "todo",      text: "Review tasks and priorities for the day" },
      { type: "todo",      text: "Clear inbox to zero" },
      { type: "divider" },
      { type: "h2",        text: "📊 Weekly Review" },
      { type: "paragraph", text: "Habits completed this week: ___ / ___" },
      { type: "h3",        text: "Which habit was hardest?" },
      { type: "paragraph", text: "" },
      { type: "h3",        text: "How will I improve next week?" },
      { type: "paragraph", text: "" },
    ],
  },

  // ── Productivity ─────────────────────────────────────────────────────────────
  {
    name: "Meeting Notes", description: "Agenda, attendees, action items, and decisions.", category: "productivity", icon: "📝",
    blocks: [
      { type: "callout",   text: "📅 Date: _____________   ·   ⏱ Time: _______   ·   📍 Location / Link: _______\n👥 Attendees: _______________________________________________\n🎯 Goal: ___________________________________________________", icon: "📝" },
      { type: "divider" },
      { type: "h2",        text: "📋 Agenda" },
      { type: "numbered",  text: "(5 min)   Welcome & context" },
      { type: "numbered",  text: "(10 min)  Main topic 1: " },
      { type: "numbered",  text: "(10 min)  Main topic 2: " },
      { type: "numbered",  text: "(5 min)   Open questions & parking lot" },
      { type: "numbered",  text: "(5 min)   Next steps & close" },
      { type: "divider" },
      { type: "h2",        text: "💬 Discussion Notes" },
      { type: "paragraph", text: "" },
      { type: "h2",        text: "✅ Decisions Made" },
      { type: "bullet",    text: "Decision: " },
      { type: "bullet",    text: "Decision: " },
      { type: "h2",        text: "⚡ Action Items" },
      { type: "todo",      text: "[ Owner: ___ ]  [ Due: ___ ]  Action: " },
      { type: "todo",      text: "[ Owner: ___ ]  [ Due: ___ ]  Action: " },
      { type: "todo",      text: "[ Owner: ___ ]  [ Due: ___ ]  Action: " },
      { type: "h2",        text: "❓ Parking Lot" },
      { type: "bullet",    text: "" },
      { type: "h2",        text: "📅 Next Meeting" },
      { type: "paragraph", text: "Date: _____________   ·   Goal: _____________" },
    ],
  },
  {
    name: "Task List", description: "Simple to-do page with checkbox blocks.", category: "productivity", icon: "☑️",
    blocks: [
      { type: "callout",   text: "📅 Date: _____________   ·   Focus area: _____________", icon: "🎯" },
      { type: "divider" },
      { type: "h2",        text: "🔴 High Priority" },
      { type: "todo",      text: "Most important task — complete this first" },
      { type: "todo",      text: "" },
      { type: "todo",      text: "" },
      { type: "h2",        text: "🟡 Medium Priority" },
      { type: "todo",      text: "" },
      { type: "todo",      text: "" },
      { type: "todo",      text: "" },
      { type: "h2",        text: "🟢 Low Priority / Nice to Have" },
      { type: "todo",      text: "" },
      { type: "todo",      text: "" },
      { type: "divider" },
      { type: "h2",        text: "🗑 Someday / Maybe" },
      { type: "bullet",    text: "Ideas and tasks to revisit later" },
      { type: "bullet",    text: "" },
    ],
  },
  {
    name: "Project Brief", description: "Goals, scope, timeline, and stakeholders for a project.", category: "productivity", icon: "📋",
    blocks: [
      { type: "callout",   text: "📌 Project: _____________   ·   👤 Owner: _____________   ·   📅 Start: _______   ·   🎯 Target: _______\n🏷 Status: Planning  /  In Progress  /  On Hold  /  Complete", icon: "📋" },
      { type: "divider" },
      { type: "h2",        text: "🎯 Problem Statement" },
      { type: "paragraph", text: "What problem does this project solve? Why does it matter now?" },
      { type: "paragraph", text: "" },
      { type: "h2",        text: "✅ Goals & Success Criteria" },
      { type: "bullet",    text: "Goal 1: " },
      { type: "bullet",    text: "Goal 2: " },
      { type: "bullet",    text: "Success looks like: " },
      { type: "h2",        text: "📐 Scope" },
      { type: "h3",        text: "In Scope" },
      { type: "bullet",    text: "" },
      { type: "bullet",    text: "" },
      { type: "h3",        text: "Out of Scope" },
      { type: "bullet",    text: "" },
      { type: "bullet",    text: "" },
      { type: "h2",        text: "👥 Stakeholders" },
      { type: "bullet",    text: "Sponsor: " },
      { type: "bullet",    text: "Lead: " },
      { type: "bullet",    text: "Core team: " },
      { type: "bullet",    text: "Informed: " },
      { type: "h2",        text: "📅 Key Milestones" },
      { type: "numbered",  text: "Kick-off — Date: " },
      { type: "numbered",  text: "Design review — Date: " },
      { type: "numbered",  text: "Build complete — Date: " },
      { type: "numbered",  text: "Launch — Date: " },
      { type: "h2",        text: "⚠️ Risks & Mitigations" },
      { type: "bullet",    text: "Risk: ___  →  Mitigation: " },
      { type: "bullet",    text: "Risk: ___  →  Mitigation: " },
      { type: "h2",        text: "💬 Notes" },
      { type: "paragraph", text: "" },
    ],
  },
  {
    name: "OKR Tracker", description: "Objectives and key results.", category: "productivity", icon: "🎯",
    blocks: [
      { type: "callout",   text: "📅 Quarter: Q_  ·  Year: ____   ·   Team / Owner: _____________", icon: "🎯" },
      { type: "divider" },
      { type: "h2",        text: "🎯 Objective 1" },
      { type: "paragraph", text: "Write your ambitious, qualitative objective here." },
      { type: "h3",        text: "Key Results" },
      { type: "todo",      text: "KR1: Increase ___ from ___ to ___   |   Progress: 0%" },
      { type: "todo",      text: "KR2: Achieve ___ by ___              |   Progress: 0%" },
      { type: "todo",      text: "KR3: Launch ___ by ___               |   Progress: 0%" },
      { type: "divider" },
      { type: "h2",        text: "🎯 Objective 2" },
      { type: "paragraph", text: "" },
      { type: "h3",        text: "Key Results" },
      { type: "todo",      text: "KR1:   |   Progress: 0%" },
      { type: "todo",      text: "KR2:   |   Progress: 0%" },
      { type: "todo",      text: "KR3:   |   Progress: 0%" },
      { type: "divider" },
      { type: "h2",        text: "🎯 Objective 3" },
      { type: "paragraph", text: "" },
      { type: "h3",        text: "Key Results" },
      { type: "todo",      text: "KR1:   |   Progress: 0%" },
      { type: "todo",      text: "KR2:   |   Progress: 0%" },
      { type: "divider" },
      { type: "h2",        text: "📊 End-of-Quarter Review" },
      { type: "h3",        text: "What we achieved" },
      { type: "bullet",    text: "" },
      { type: "h3",        text: "What we missed and why" },
      { type: "bullet",    text: "" },
    ],
  },

  // ── Project Management ───────────────────────────────────────────────────────
  {
    name: "Project Tracker", description: "Track tasks with status, priority, assignee, and due date.", category: "project_mgmt", icon: "🗂️",
    blocks: [
      { type: "callout",   text: "📌 Project: _____________   ·   👤 Owner: _____________   ·   📅 Due: _____________\n🏷 Status: 🟡 Planning   🔵 In Progress   🟢 Complete   🔴 Blocked", icon: "🗂️" },
      { type: "divider" },
      { type: "h2",        text: "📋 Overview" },
      { type: "paragraph", text: "Briefly describe this project and what it aims to achieve." },
      { type: "paragraph", text: "" },
      { type: "h2",        text: "🚀 Milestones" },
      { type: "todo",      text: "📍 Milestone 1: _______________   Due: ___________" },
      { type: "todo",      text: "📍 Milestone 2: _______________   Due: ___________" },
      { type: "todo",      text: "📍 Milestone 3: _______________   Due: ___________" },
      { type: "todo",      text: "📍 Launch:      _______________   Due: ___________" },
      { type: "h2",        text: "⚡ Open Issues" },
      { type: "bullet",    text: "🔴 Blocker: " },
      { type: "bullet",    text: "🟡 Risk: " },
      { type: "bullet",    text: "🔵 Question: " },
      { type: "h2",        text: "✅ Completed" },
      { type: "bullet",    text: "" },
      { type: "h2",        text: "💬 Status Updates" },
      { type: "paragraph", text: "📅 Date: ___  —  Update: " },
    ],
  },
  {
    name: "Sprint Board", description: "Kanban board pre-configured for sprint workflow.", category: "project_mgmt", icon: "🏃",
    blocks: [
      { type: "callout",   text: "🗓 Sprint: #___   ·   Dates: ___________ → ___________   ·   Team: _____________\n🎯 Sprint Goal: ___________________________________________________", icon: "🏃" },
      { type: "divider" },
      { type: "h2",        text: "📥 Sprint Backlog" },
      { type: "todo",      text: "[ P1 ]  Task: ___________________________   Owner: ___   Points: __" },
      { type: "todo",      text: "[ P1 ]  Task: ___________________________   Owner: ___   Points: __" },
      { type: "todo",      text: "[ P2 ]  Task: ___________________________   Owner: ___   Points: __" },
      { type: "todo",      text: "[ P2 ]  Task: ___________________________   Owner: ___   Points: __" },
      { type: "h2",        text: "🔄 In Progress" },
      { type: "todo",      text: "Task: ___________________________   Owner: ___   Started: ____" },
      { type: "todo",      text: "Task: ___________________________   Owner: ___   Started: ____" },
      { type: "h2",        text: "👀 In Review" },
      { type: "todo",      text: "Task: ___________________________   Owner: ___   PR / Link: _____" },
      { type: "h2",        text: "✅ Done" },
      { type: "todo",      text: "Completed task example" },
      { type: "divider" },
      { type: "h2",        text: "🔁 Retrospective" },
      { type: "h3",        text: "What went well? 🟢" },
      { type: "bullet",    text: "" },
      { type: "h3",        text: "What could be improved? 🟡" },
      { type: "bullet",    text: "" },
      { type: "h3",        text: "Action items for next sprint" },
      { type: "todo",      text: "" },
    ],
  },
  {
    name: "Bug Tracker", description: "Track bugs with severity and status.", category: "project_mgmt", icon: "🐛",
    blocks: [
      { type: "callout",   text: "🔴 Severity: Critical  /  High  /  Medium  /  Low\n📅 Reported: _______   ·   👤 Reporter: _______   ·   🏷 Status: Open  /  In Progress  /  Fixed\n📦 Version: _______   ·   🖥 Environment: Production  /  Staging  /  Local", icon: "🐛" },
      { type: "divider" },
      { type: "h2",        text: "🐛 Description" },
      { type: "paragraph", text: "Describe the bug clearly. What is broken? What was expected?" },
      { type: "paragraph", text: "" },
      { type: "h2",        text: "🔄 Steps to Reproduce" },
      { type: "numbered",  text: "Go to ___" },
      { type: "numbered",  text: "Click / do ___" },
      { type: "numbered",  text: "Observe: ___" },
      { type: "h2",        text: "✅ Expected Behavior" },
      { type: "paragraph", text: "" },
      { type: "h2",        text: "❌ Actual Behavior" },
      { type: "paragraph", text: "" },
      { type: "h2",        text: "📸 Screenshots / Logs" },
      { type: "paragraph", text: "Attach screenshots or paste error logs here." },
      { type: "h2",        text: "🔧 Fix Notes" },
      { type: "paragraph", text: "Root cause: " },
      { type: "paragraph", text: "Fix applied: " },
      { type: "paragraph", text: "Fixed by: ___   ·   Fixed on: ___   ·   PR / Commit: ___" },
    ],
  },
  {
    name: "Content Calendar", description: "Calendar view database for content publishing schedule.", category: "project_mgmt", icon: "📆",
    blocks: [
      { type: "callout",   text: "📅 Month: _____________   ·   📢 Channels: Blog  /  Twitter  /  LinkedIn  /  Email  /  YouTube\n👤 Owner: _____________   ·   🎯 Monthly Theme: _____________", icon: "📆" },
      { type: "divider" },
      { type: "h2",        text: "💡 Content Ideas Backlog" },
      { type: "bullet",    text: "Idea: _____________   Format: ____   Channel: ____   Priority: High / Medium / Low" },
      { type: "bullet",    text: "Idea: _____________   Format: ____   Channel: ____   Priority: High / Medium / Low" },
      { type: "bullet",    text: "Idea: _____________   Format: ____   Channel: ____   Priority: High / Medium / Low" },
      { type: "h2",        text: "📅 Publishing Schedule" },
      { type: "h3",        text: "Week 1" },
      { type: "todo",      text: "Title:   |   Channel:   |   Due:   |   Status: Draft" },
      { type: "todo",      text: "Title:   |   Channel:   |   Due:   |   Status: Draft" },
      { type: "h3",        text: "Week 2" },
      { type: "todo",      text: "Title:   |   Channel:   |   Due:   |   Status: Draft" },
      { type: "todo",      text: "Title:   |   Channel:   |   Due:   |   Status: Draft" },
      { type: "h3",        text: "Week 3" },
      { type: "todo",      text: "Title:   |   Channel:   |   Due:   |   Status: Draft" },
      { type: "todo",      text: "Title:   |   Channel:   |   Due:   |   Status: Draft" },
      { type: "h3",        text: "Week 4" },
      { type: "todo",      text: "Title:   |   Channel:   |   Due:   |   Status: Draft" },
      { type: "todo",      text: "Title:   |   Channel:   |   Due:   |   Status: Draft" },
      { type: "divider" },
      { type: "h2",        text: "📊 Monthly Performance" },
      { type: "bullet",    text: "Total pieces published: " },
      { type: "bullet",    text: "Best performing piece: " },
      { type: "bullet",    text: "Key learnings: " },
    ],
  },

  // ── Team & Knowledge ─────────────────────────────────────────────────────────
  {
    name: "Team Wiki", description: "Structured knowledge base with sections and subpages.", category: "project_mgmt", icon: "🏛️",
    blocks: [
      { type: "paragraph", text: "👋 Welcome to the team knowledge base. Find everything you need to get up to speed and stay aligned." },
      { type: "divider" },
      { type: "h2",        text: "🚀 Getting Started" },
      { type: "numbered",  text: "Read the Company Handbook" },
      { type: "numbered",  text: "Set up your tools (see Tools & Access below)" },
      { type: "numbered",  text: "Schedule intro meetings with key team members" },
      { type: "numbered",  text: "Join the main communication channels" },
      { type: "h2",        text: "📋 Processes & Guidelines" },
      { type: "h3",        text: "How we work" },
      { type: "bullet",    text: "Stand-ups: Daily at ___ via ___" },
      { type: "bullet",    text: "Planning: Every ___ at ___" },
      { type: "bullet",    text: "Retrospectives: Every ___ at ___" },
      { type: "h3",        text: "Communication norms" },
      { type: "bullet",    text: "Real-time chat: " },
      { type: "bullet",    text: "Async updates: " },
      { type: "bullet",    text: "Response time expectation: within ___" },
      { type: "h2",        text: "🛠 Tools & Access" },
      { type: "bullet",    text: "Project management: " },
      { type: "bullet",    text: "Design: " },
      { type: "bullet",    text: "Code / Repos: " },
      { type: "bullet",    text: "Communication: " },
      { type: "bullet",    text: "Documentation: " },
      { type: "h2",        text: "❓ FAQs" },
      { type: "h3",        text: "How do I request time off?" },
      { type: "paragraph", text: "" },
      { type: "h3",        text: "Who do I contact for IT / access issues?" },
      { type: "paragraph", text: "" },
      { type: "h3",        text: "Where are design assets stored?" },
      { type: "paragraph", text: "" },
    ],
  },
  {
    name: "Company Handbook", description: "Policies, culture, and onboarding info.", category: "project_mgmt", icon: "📖",
    blocks: [
      { type: "paragraph", text: "Everything you need to know about working here. Last updated: _____________" },
      { type: "divider" },
      { type: "h2",        text: "🌟 Our Mission" },
      { type: "paragraph", text: "We exist to _______________________________________________" },
      { type: "h2",        text: "💡 Core Values" },
      { type: "bullet",    text: "Value 1: ___   —   What this means in practice: " },
      { type: "bullet",    text: "Value 2: ___   —   What this means in practice: " },
      { type: "bullet",    text: "Value 3: ___   —   What this means in practice: " },
      { type: "bullet",    text: "Value 4: ___   —   What this means in practice: " },
      { type: "h2",        text: "🏢 Culture & Ways of Working" },
      { type: "h3",        text: "Working hours" },
      { type: "paragraph", text: "Core hours: ___   ·   Flexibility: ___" },
      { type: "h3",        text: "Remote / in-office policy" },
      { type: "paragraph", text: "" },
      { type: "h3",        text: "Meetings" },
      { type: "paragraph", text: "Recurring meetings: ___   ·   Meeting-free days: ___" },
      { type: "h2",        text: "🎁 Benefits & Perks" },
      { type: "bullet",    text: "Health: " },
      { type: "bullet",    text: "PTO: " },
      { type: "bullet",    text: "Learning & development: " },
      { type: "bullet",    text: "Equipment stipend: " },
      { type: "bullet",    text: "Other perks: " },
      { type: "h2",        text: "📋 Onboarding Checklist" },
      { type: "h3",        text: "Week 1" },
      { type: "todo",      text: "Meet your manager for a 1:1" },
      { type: "todo",      text: "Set up all accounts and tools" },
      { type: "todo",      text: "Read Company Handbook end-to-end" },
      { type: "todo",      text: "Meet the immediate team" },
      { type: "h3",        text: "Weeks 2–4" },
      { type: "todo",      text: "Complete onboarding training modules" },
      { type: "todo",      text: "Shadow key team members" },
      { type: "todo",      text: "Set 30-60-90 day goals with manager" },
      { type: "h2",        text: "📞 Key Contacts" },
      { type: "bullet",    text: "CEO: " },
      { type: "bullet",    text: "HR / People Ops: " },
      { type: "bullet",    text: "IT Support: " },
    ],
  },
  {
    name: "Meeting Agenda", description: "Pre-meeting agenda with action item tracking.", category: "project_mgmt", icon: "🗓️",
    blocks: [
      { type: "callout",   text: "📅 Date: _____________   ·   ⏱ Time: _______   ·   📍 Location / Link: _______\n👤 Facilitator: _____________   ·   📝 Note-taker: _____________\n👥 Attendees: _______________________________________________", icon: "🗓️" },
      { type: "divider" },
      { type: "h2",        text: "🎯 Meeting Goal" },
      { type: "paragraph", text: "By end of this meeting we will have: " },
      { type: "h2",        text: "📋 Agenda Items" },
      { type: "numbered",  text: "(5 min)   Welcome & context setting" },
      { type: "numbered",  text: "(10 min)  Topic 1: _______________" },
      { type: "numbered",  text: "(10 min)  Topic 2: _______________" },
      { type: "numbered",  text: "(10 min)  Topic 3: _______________" },
      { type: "numbered",  text: "(5 min)   Open Q&A" },
      { type: "numbered",  text: "(5 min)   Next steps & close" },
      { type: "h2",        text: "📚 Pre-read Materials" },
      { type: "bullet",    text: "" },
      { type: "h2",        text: "✅ Expected Outcomes" },
      { type: "bullet",    text: "Decision needed on: " },
      { type: "bullet",    text: "Information to share: " },
      { type: "bullet",    text: "Input needed from: " },
      { type: "divider" },
      { type: "h2",        text: "📝 Meeting Notes" },
      { type: "paragraph", text: "" },
      { type: "h2",        text: "⚡ Action Items" },
      { type: "todo",      text: "[ Owner: ___ ]  [ Due: ___ ]  " },
      { type: "todo",      text: "[ Owner: ___ ]  [ Due: ___ ]  " },
    ],
  },
  {
    name: "Decision Log", description: "Log decisions with context and outcome.", category: "project_mgmt", icon: "⚖️",
    blocks: [
      { type: "callout",   text: "📅 Date: _____________   ·   👤 Owner: _____________   ·   🏷 Status: Proposed  /  Approved  /  Rejected", icon: "⚖️" },
      { type: "divider" },
      { type: "h2",        text: "📌 The Decision" },
      { type: "paragraph", text: "State the decision clearly in one sentence." },
      { type: "paragraph", text: "" },
      { type: "h2",        text: "📖 Context & Background" },
      { type: "paragraph", text: "Why did we need to make this decision?" },
      { type: "paragraph", text: "" },
      { type: "h2",        text: "⚖️ Options Considered" },
      { type: "h3",        text: "Option A" },
      { type: "bullet",    text: "✅ Pros: " },
      { type: "bullet",    text: "❌ Cons: " },
      { type: "h3",        text: "Option B" },
      { type: "bullet",    text: "✅ Pros: " },
      { type: "bullet",    text: "❌ Cons: " },
      { type: "h3",        text: "Option C" },
      { type: "bullet",    text: "✅ Pros: " },
      { type: "bullet",    text: "❌ Cons: " },
      { type: "h2",        text: "✅ Decision & Rationale" },
      { type: "paragraph", text: "We chose Option ___  because: " },
      { type: "paragraph", text: "" },
      { type: "h2",        text: "📋 Next Steps" },
      { type: "todo",      text: "" },
      { type: "todo",      text: "" },
      { type: "h2",        text: "🔁 Review Date" },
      { type: "paragraph", text: "Revisit this decision on: _____________" },
    ],
  },

  // ── CRM ──────────────────────────────────────────────────────────────────────
  {
    name: "Contact Database", description: "People database with company, last contact, and notes.", category: "sales", icon: "👥",
    blocks: [
      { type: "paragraph", text: "Track and nurture your professional and personal network." },
      { type: "divider" },
      { type: "h2",        text: "👤 Contact Entry" },
      { type: "callout",   text: "Name: _______________   ·   Company: _______________   ·   Role: _______________\n📧 Email: _______________   ·   📱 Phone: _______________\n🏷 Tags: colleague  /  client  /  partner  /  investor  /  mentor\n📅 Last contacted: _______________   ·   Next follow-up: _______________", icon: "👤" },
      { type: "h3",        text: "Relationship Notes" },
      { type: "paragraph", text: "How did we meet? What do we have in common?" },
      { type: "paragraph", text: "" },
      { type: "h3",        text: "Conversation History" },
      { type: "bullet",    text: "📅 Date: ___  —  " },
      { type: "bullet",    text: "📅 Date: ___  —  " },
      { type: "divider" },
      { type: "h2",        text: "📋 How to Use This Template" },
      { type: "numbered",  text: "Create one page per contact (or use a database with each row as a contact)" },
      { type: "numbered",  text: "Use tags to filter by relationship type" },
      { type: "numbered",  text: "Set follow-up dates and review weekly" },
      { type: "numbered",  text: "Log every interaction so you never lose context" },
      { type: "h2",        text: "🌟 Key Contacts to Follow Up" },
      { type: "bullet",    text: "Name — Company — Next follow-up: ___" },
      { type: "bullet",    text: "Name — Company — Next follow-up: ___" },
      { type: "bullet",    text: "Name — Company — Next follow-up: ___" },
    ],
  },
  {
    name: "Company Tracker", description: "Track companies and organizations you interact with.", category: "sales", icon: "🏢",
    blocks: [
      { type: "paragraph", text: "Track companies and organizations you work with, sell to, or want to build relationships with." },
      { type: "divider" },
      { type: "h2",        text: "🏢 Company Overview" },
      { type: "callout",   text: "Company: _______________   ·   Website: _______________\nIndustry: _______________   ·   Size: ___ employees\nHQ Location: _______________   ·   Stage: Startup / Scale-up / Enterprise", icon: "🏢" },
      { type: "h3",        text: "Key Contacts at This Company" },
      { type: "bullet",    text: "Name — Role — Email — Last contact: ___" },
      { type: "bullet",    text: "Name — Role — Email — Last contact: ___" },
      { type: "h2",        text: "🤝 Relationship Status" },
      { type: "paragraph", text: "🏷 Status: Prospect  /  Active Client  /  Partner  /  Past Client" },
      { type: "paragraph", text: "📅 First contact: ___   ·   Last contact: ___   ·   Next follow-up: ___" },
      { type: "h2",        text: "📝 Interaction History" },
      { type: "bullet",    text: "📅 Date: ___  —  Type: Call / Email / Meeting  —  Summary: " },
      { type: "bullet",    text: "📅 Date: ___  —  Type: Call / Email / Meeting  —  Summary: " },
      { type: "h2",        text: "💼 Opportunities" },
      { type: "bullet",    text: "Opportunity: ___   Value: ___   Stage: ___   Close: ___" },
      { type: "h2",        text: "💬 Notes" },
      { type: "paragraph", text: "" },
    ],
  },
];

async function main() {
  const [{ db }, { templates }, { eq }] = await Promise.all([
    import("@/lib/db"),
    import("@/lib/db/schema"),
    import("drizzle-orm"),
  ]);

  console.log("Deleting existing built-in templates…");
  await db.delete(templates).where(eq(templates.isBuiltIn, true));

  console.log("Seeding 19 built-in templates…");

  const rows = TEMPLATES.map((t) => ({
    name:         t.name,
    description:  t.description,
    category:     t.category,
    isBuiltIn:    true,
    status:       "published" as const,
    workspaceId:  null,
    createdBy:    null,
    pageSnapshot: snap(t.name, t.icon, t.blocks),
  }));

  await db.insert(templates).values(rows);
  console.log(`✓ Seeded ${rows.length} templates.`);
  process.exit(0);
}

main().catch((err) => {
  console.error("Failed:", err);
  process.exit(1);
});
